n = input('write somenthing: ')
print('É letra?', n.isalpha())
print('Está em maiusculo?', n.isupper())
print('Está em minusculo?', n.islower())
print('É númerico?', n.isnumeric())
print('É decimal?', n.isdecimal())
print('Só tem espaços?', n.isspace())
print('É alfanúmerico?', n.isalnum())
